# Generated by Django 2.1.3 on 2018-11-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('sender', models.TextField()),
                ('message', models.TextField()),
                ('date', models.DateField()),
                ('read', models.BooleanField()),
            ],
        ),
    ]
