# Generated by Django 2.1.3 on 2018-11-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelloDjangoApp', '0002_auto_20181113_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(default='Nov 14, 2018 at 09:42 AM'),
        ),
    ]
